# fly.toml app configuration file generated for budget-management on 2023-06-10T18:24:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "budget-management"
primary_region = "lhr"
console_command = "/rails/bin/rails console"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
